source 'https://rubygems.org'

gem 'github-pages', '~> 232'
gem 'jekyll', '~> 3.10'
gem 'jekyll-feed'
gem 'jekyll-paginate-v2'
gem 'jekyll-mentions'
gem 'jekyll-email-protect'
gem 'jekyll-figure'
gem 'jekyll/scholar'
